# Generated by Django 4.1 on 2022-08-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dict_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WORDS',
            new_name='WORD',
        ),
    ]
