# Generated by Django 4.1 on 2022-08-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dict_app', '0002_rename_words_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='meaning',
            name='word',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dict_app.word'),
        ),
    ]
