# Generated by Django 4.1 on 2022-08-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dict_app', '0003_meaning_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='WORD_MEANING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=300)),
                ('synonyms', models.CharField(max_length=200)),
                ('antonyms', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='MEANING',
        ),
        migrations.DeleteModel(
            name='WORD',
        ),
    ]
